import Head from 'next/head'
import '@/styles/globals.css'
import Navbar from '../components/Navbar'
import { useState, createContext } from "react"

export const UserContext = createContext()

export default function App({ Component, pageProps }) {
  const [user, setUser] = useState({
    jwt: '',
  })

  return (
      <UserContext.Provider value={{user, setUser}}>
        <Head>
          <title>My work buddy</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Component {...pageProps} />
      </UserContext.Provider>
    )
}
