import Head from 'next/head'
import '@/styles/globals.css'
import Navbar from '../components/Navbar'
import { useState, createContext} from "react"
import { ToastContainer } from 'react-toastify'

import 'react-toastify/dist/ReactToastify.css';

export const UserContext = createContext()

export default function App({ Component, pageProps }) {
  const [user, setUser] = useState({
    role: '',
    iat: '',
    jti: ''
  })

  const [roles, setRoles] = useState({
    manager: "a94c4a3f-c803-460b-a6c4-8bcaa7c3b4ed",
    newemployee: "1bf7e39b-2a3f-4c79-80ac-fe5181e20102",
    oldemployee: "3809eb83-ab0c-4d74-bb0e-575be69d8933"
  })

  return (
      <UserContext.Provider value={{user, setUser, roles, setRoles}}>
        <Head>
          <title>My work buddy</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <ToastContainer 
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <Component {...pageProps} />
      </UserContext.Provider>
    )
}
